services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'

  postgres:
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=chat-genie
      - POSTGRES_USER=chat-genie
    ports:
      - '49974:5432'
