spring:
  application.name: ChaTGenie
  ai:
    ollama:
      chat:
        model: 'llama3.1:8b'

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
