routes:
  chat-genie-url: http://chat-genie:8080/

spring:
  application.name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:/jwt_key.pub
          jws-algorithms: RS512
  cloud:
    gateway:
      routes:
        - id: chat-genie-generate-suggestion
          predicates:
            - Path=/api/generate/suggestions,/api/generate/suggestions/system-text
          uri: ${routes.chat-genie-url}
          filters:
            - AddRequestParameter=userId, {principal_name}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
